CREATE DATABASE IF NOT EXISTS bookstore;

USE bookstore;
CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(255) NOT NULL PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    enabled TINYINT(1) NOT NULL
);


CREATE TABLE IF NOT EXISTS authorities (
	username VARCHAR(255) NOT NULL,
	authority VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
	id bigint generated by default as identity,
	authors varchar(255) not null,
	isbn varchar(255) not null,
	name varchar(255) not null,
	price decimal(19,2) not null,
	published_on date not null,
	publisher varchar(255) not null,
	primary key (id)
);
    
CREATE TABLE IF NOT EXISTS customers (
	id bigint generated by default as identity,
	city varchar(60) not null,
	country_region varchar(55) not null,
	email varchar(254) not null,
	name varchar(50) not null,
	phone_number varchar(15) not null,
	postal_code varchar(18) not null,
	street_and_house_number varchar(100) not null,
	surname varchar(50) not null,
	primary key (id)
);
    
CREATE TABLE IF NOT EXISTS orders (
	id bigint generated by default as identity,
	order_date date not null,
	book_id bigint,
	customer_id bigint,
	primary key (id)
);

INSERT INTO users (username, password, enabled) 
	VALUES ('admin', '{noop}admin', 1);
	


INSERT INTO authorities (username, authority) 
	VALUES ('admin', 'ADMIN');
